### ISSUE TITLE
Warning --> array_keys() expects parameter 1 to be array, bool given /system/database/DB_query_builder.php 1561

### ISSUE THREAD

**Issue by petroutassos** [amir-ranglerz/CodeIgniter-Insert-Batch-on-DUPLICATE-KEY-Update#1]
Getting the following if array is empty
`ERROR - 2020-11-07 01:35:19 --> Severity: Warning --> array_keys() expects parameter 1 to be array, bool given /system/database/DB_query_builder.php 1561
ERROR - 2020-11-07 01:35:19 --> Severity: Warning --> sort() expects parameter 1 to be array, null given /system/database/DB_query_builder.php 1562
ERROR - 2020-11-07 01:35:19 --> Severity: Warning --> Invalid argument supplied for foreach() /system/database/DB_query_builder.php 1590
`

**Comment by petroutassos** [comment]
Please replace line 23 on file _MY_DB_mysqli_driver.php_ with the following line

`if (!is_null($set) && !empty($set)) {`

**Comment by AmirHuxain** [comment]
Added extra check on array
