### ISSUE TITLE
Can I change 100 to 10000 ?

### ISSUE THREAD

**Issue by ghost** [amir-ranglerz/CodeIgniter-Insert-Batch-on-DUPLICATE-KEY-Update#2]
for ($i = 0, $total = count($this->qb_set); $i < $total; $i = $i + 10000) {

            $sql = $this->_insert_on_duplicate_update_batch($this->protect_identifiers($table, TRUE, NULL, FALSE), $this->qb_keys, array_slice($this->qb_set, $i, 10000));

**Comment by AmirHuxain** [comment]
Yes, you can. `100` is the default batch size of the official `insert_batch` function of CodeIgniter.
